<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '../utils/request'; import type { Result } from '../api/types'
interface Family{userId:string;displayName:string};interface Elder{elderId:string;name:string};interface Assignment{userId:string;familyName:string;elderId:string;elderName:string;consentGranted:boolean}
const items=ref<Assignment[]>([]),families=ref<Family[]>([]),elders=ref<Elder[]>([]),open=ref(false),loading=ref(false),form=ref({userId:'',elderId:''})
async function load(){loading.value=true;try{const [a,f,e]=await Promise.all([request.get<Result<Assignment[]>>('/admin/family-assignments'),request.get<Result<Family[]>>('/admin/families'),request.get<Result<Elder[]>>('/elders')]);items.value=a.data.data;families.value=f.data.data;elders.value=e.data.data}finally{loading.value=false}}async function create(){await request.post('/admin/family-assignments',form.value);open.value=false;ElMessage.success('绑定已创建');load()}async function unbind(item:Assignment){await ElMessageBox.confirm(`确认解除 ${item.familyName} 与 ${item.elderName} 的授权关系？`,'解除授权',{type:'warning'});await request.delete(`/admin/family-assignments/${item.userId}/${item.elderId}`);ElMessage.success('授权已解除');load()}onMounted(load)
</script>
<template><div class="page"><div class="page-heading"><div><p class="eyebrow">权限与隐私</p><h1>家属授权绑定</h1><p class="muted">家属仅可访问授权范围内的老人档案、告警和报告。</p></div><el-button type="primary" @click="open=true">创建绑定</el-button></div><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe><el-table-column prop="familyName" label="家属账号"/><el-table-column prop="elderName" label="老人"/><el-table-column label="授权范围"><template #default>监测、告警、风险报告</template></el-table-column><el-table-column label="隐私授权"><template #default="{row}"><el-tag :type="row.consentGranted?'success':'warning'">{{row.consentGranted?'已取得授权':'尚未授权'}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link type="danger" @click="unbind(row)">解除绑定</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="open" title="创建家属—老人绑定" width="460px"><el-form label-width="90px"><el-form-item label="家属"><el-select v-model="form.userId" class="w-full"><el-option v-for="item in families" :key="item.userId" :label="item.displayName" :value="item.userId"/></el-select></el-form-item><el-form-item label="老人"><el-select v-model="form.elderId" class="w-full"><el-option v-for="item in elders" :key="item.elderId" :label="item.name" :value="item.elderId"/></el-select></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" @click="create">确认绑定</el-button></template></el-dialog></div></template>
